// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditLog = `-- name: AppendAuditLog :exec
INSERT INTO audit_log (
    id, occurred_at, tenant_id, actor_id, actor_type, action,
    resource_type, resource_id, outcome, ip, user_agent, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type AppendAuditLogParams struct {
	ID           pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   string
	Outcome      string
	Ip           string
	UserAgent    string
	Metadata     []byte
}

func (q *Queries) AppendAuditLog(ctx context.Context, arg AppendAuditLogParams) error {
	_, err := q.db.Exec(ctx, appendAuditLog,
		arg.ID,
		arg.OccurredAt,
		arg.TenantID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, occurred_at, tenant_id, actor_id, actor_type, action,
       resource_type, resource_id, outcome, ip, user_agent, metadata
FROM audit_log
WHERE ($1::UUID IS NULL OR tenant_id = $1::UUID)
  AND ($2::UUID IS NULL OR actor_id = $2::UUID)
  AND ($3::TEXT IS NULL OR action = $3::TEXT)
ORDER BY occurred_at DESC
LIMIT $4
`

type ListAuditLogParams struct {
	TenantID pgtype.UUID
	ActorID  pgtype.UUID
	Action   pgtype.Text
	Lim      int32
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.TenantID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Outcome,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
