// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	AuthorID       pgtype.UUID
	Title          string
	Slug           string
	Status         string
	Tags           []byte
	Deadline       pgtype.Timestamptz
	ScheduledAt    pgtype.Timestamptz
	PublishedAt    pgtype.Timestamptz
	Excerpt        pgtype.Text
	CoverImage     []byte
	Attachments    []byte
	PublishHistory []byte
	Revision       int32
	RevisionSha    pgtype.Text
	Content        string
	TelegramUrl    pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
