// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO oauth_accounts (
    id, user_id, provider, external_id, email, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateOAuthAccountParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Provider   string
	ExternalID string
	Email      string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ExternalID,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :execrows
DELETE FROM oauth_accounts WHERE id = $1
`

func (q *Queries) DeleteOAuthAccount(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthAccountByExternalID = `-- name: GetOAuthAccountByExternalID :one
SELECT id, user_id, provider, external_id, email, created_at
FROM oauth_accounts
WHERE provider = $1 AND external_id = $2
`

type GetOAuthAccountByExternalIDParams struct {
	Provider   string
	ExternalID string
}

func (q *Queries) GetOAuthAccountByExternalID(ctx context.Context, arg GetOAuthAccountByExternalIDParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByExternalID, arg.Provider, arg.ExternalID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthAccountsByUser = `-- name: ListOAuthAccountsByUser :many
SELECT id, user_id, provider, external_id, email, created_at
FROM oauth_accounts
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOAuthAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, listOAuthAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthAccount
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ExternalID,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
