// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextOutbox = `-- name: ClaimNextOutbox :one
UPDATE outbox_entries
SET status = 'in_flight', updated_at = $1
WHERE id = (
    SELECT oe.id FROM outbox_entries oe
    WHERE oe.status = 'pending' AND oe.next_attempt_at <= $2
    ORDER BY oe.next_attempt_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, post_id, tenant_id, kind, status, attempts, max_attempts,
          next_attempt_at, last_error, created_at, updated_at
`

type ClaimNextOutboxParams struct {
	UpdatedAt     pgtype.Timestamptz
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) ClaimNextOutbox(ctx context.Context, arg ClaimNextOutboxParams) (OutboxEntry, error) {
	row := q.db.QueryRow(ctx, claimNextOutbox, arg.UpdatedAt, arg.NextAttemptAt)
	var i OutboxEntry
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.TenantID,
		&i.Kind,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutbox = `-- name: CreateOutbox :exec
INSERT INTO outbox_entries (
    id, post_id, tenant_id, kind, status, attempts, max_attempts,
    next_attempt_at, last_error, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateOutboxParams struct {
	ID            pgtype.UUID
	PostID        pgtype.UUID
	TenantID      pgtype.UUID
	Kind          string
	Status        string
	Attempts      int32
	MaxAttempts   int32
	NextAttemptAt pgtype.Timestamptz
	LastError     string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateOutbox(ctx context.Context, arg CreateOutboxParams) error {
	_, err := q.db.Exec(ctx, createOutbox,
		arg.ID,
		arg.PostID,
		arg.TenantID,
		arg.Kind,
		arg.Status,
		arg.Attempts,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOutboxByID = `-- name: GetOutboxByID :one
SELECT id, post_id, tenant_id, kind, status, attempts, max_attempts,
       next_attempt_at, last_error, created_at, updated_at
FROM outbox_entries WHERE id = $1
`

func (q *Queries) GetOutboxByID(ctx context.Context, id pgtype.UUID) (OutboxEntry, error) {
	row := q.db.QueryRow(ctx, getOutboxByID, id)
	var i OutboxEntry
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.TenantID,
		&i.Kind,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutboxAll = `-- name: ListOutboxAll :many
SELECT id, post_id, tenant_id, kind, status, attempts, max_attempts,
       next_attempt_at, last_error, created_at, updated_at
FROM outbox_entries
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListOutboxAll(ctx context.Context, limit int32) ([]OutboxEntry, error) {
	rows, err := q.db.Query(ctx, listOutboxAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEntry
	for rows.Next() {
		var i OutboxEntry
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.TenantID,
			&i.Kind,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxByStatus = `-- name: ListOutboxByStatus :many
SELECT id, post_id, tenant_id, kind, status, attempts, max_attempts,
       next_attempt_at, last_error, created_at, updated_at
FROM outbox_entries
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOutboxByStatusParams struct {
	Status string
	Limit  int32
}

func (q *Queries) ListOutboxByStatus(ctx context.Context, arg ListOutboxByStatusParams) ([]OutboxEntry, error) {
	rows, err := q.db.Query(ctx, listOutboxByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEntry
	for rows.Next() {
		var i OutboxEntry
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.TenantID,
			&i.Kind,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxDone = `-- name: MarkOutboxDone :execrows
UPDATE outbox_entries
SET status = 'done', updated_at = $1
WHERE id = $2
`

type MarkOutboxDoneParams struct {
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) MarkOutboxDone(ctx context.Context, arg MarkOutboxDoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxDone, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :execrows
UPDATE outbox_entries
SET status = 'failed', last_error = $1, updated_at = $2
WHERE id = $3
`

type MarkOutboxFailedParams struct {
	LastError string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxFailed, arg.LastError, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxRetry = `-- name: MarkOutboxRetry :execrows
UPDATE outbox_entries
SET status = 'pending', attempts = $1, next_attempt_at = $2, last_error = $3, updated_at = $4
WHERE id = $5
`

type MarkOutboxRetryParams struct {
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LastError     string
	UpdatedAt     pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxRetry,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
