// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (
    id, tenant_id, author_id, title, slug, status,
    tags, deadline, scheduled_at, published_at,
    excerpt, cover_image, attachments, publish_history,
    revision, revision_sha, content, telegram_url,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20
)
`

type CreatePostParams struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	AuthorID       pgtype.UUID
	Title          string
	Slug           string
	Status         string
	Tags           []byte
	Deadline       pgtype.Timestamptz
	ScheduledAt    pgtype.Timestamptz
	PublishedAt    pgtype.Timestamptz
	Excerpt        pgtype.Text
	CoverImage     []byte
	Attachments    []byte
	PublishHistory []byte
	Revision       int32
	RevisionSha    pgtype.Text
	Content        string
	TelegramUrl    pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.ID,
		arg.TenantID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Tags,
		arg.Deadline,
		arg.ScheduledAt,
		arg.PublishedAt,
		arg.Excerpt,
		arg.CoverImage,
		arg.Attachments,
		arg.PublishHistory,
		arg.Revision,
		arg.RevisionSha,
		arg.Content,
		arg.TelegramUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts WHERE id = $1 AND tenant_id = $2
`

type DeletePostParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, tenant_id, author_id, title, slug, status, tags, deadline, scheduled_at, published_at, excerpt, cover_image, attachments, publish_history, revision, revision_sha, content, telegram_url, created_at, updated_at FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Tags,
		&i.Deadline,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Excerpt,
		&i.CoverImage,
		&i.Attachments,
		&i.PublishHistory,
		&i.Revision,
		&i.RevisionSha,
		&i.Content,
		&i.TelegramUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByIDInTenant = `-- name: GetPostByIDInTenant :one
SELECT id, tenant_id, author_id, title, slug, status, tags, deadline, scheduled_at, published_at, excerpt, cover_image, attachments, publish_history, revision, revision_sha, content, telegram_url, created_at, updated_at FROM posts WHERE id = $1 AND tenant_id = $2
`

type GetPostByIDInTenantParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) GetPostByIDInTenant(ctx context.Context, arg GetPostByIDInTenantParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByIDInTenant, arg.ID, arg.TenantID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Tags,
		&i.Deadline,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Excerpt,
		&i.CoverImage,
		&i.Attachments,
		&i.PublishHistory,
		&i.Revision,
		&i.RevisionSha,
		&i.Content,
		&i.TelegramUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, tenant_id, author_id, title, slug, status, tags, deadline, scheduled_at, published_at, excerpt, cover_image, attachments, publish_history, revision, revision_sha, content, telegram_url, created_at, updated_at FROM posts WHERE tenant_id = $1 AND slug = $2
`

type GetPostBySlugParams struct {
	TenantID pgtype.UUID
	Slug     string
}

func (q *Queries) GetPostBySlug(ctx context.Context, arg GetPostBySlugParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, arg.TenantID, arg.Slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Tags,
		&i.Deadline,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Excerpt,
		&i.CoverImage,
		&i.Attachments,
		&i.PublishHistory,
		&i.Revision,
		&i.RevisionSha,
		&i.Content,
		&i.TelegramUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const postExistsByID = `-- name: PostExistsByID :one
SELECT EXISTS(SELECT 1 FROM posts WHERE id = $1) AS exists
`

func (q *Queries) PostExistsByID(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, postExistsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePost = `-- name: UpdatePost :execrows
UPDATE posts SET
    author_id = $2,
    title = $3,
    slug = $4,
    status = $5,
    tags = $6,
    deadline = $7,
    scheduled_at = $8,
    published_at = $9,
    excerpt = $10,
    cover_image = $11,
    attachments = $12,
    publish_history = $13,
    revision = $14,
    revision_sha = $15,
    content = $16,
    telegram_url = $17,
    updated_at = $18
WHERE id = $1 AND tenant_id = $19 AND revision = $20
`

type UpdatePostParams struct {
	ID             pgtype.UUID
	AuthorID       pgtype.UUID
	Title          string
	Slug           string
	Status         string
	Tags           []byte
	Deadline       pgtype.Timestamptz
	ScheduledAt    pgtype.Timestamptz
	PublishedAt    pgtype.Timestamptz
	Excerpt        pgtype.Text
	CoverImage     []byte
	Attachments    []byte
	PublishHistory []byte
	Revision       int32
	RevisionSha    pgtype.Text
	Content        string
	TelegramUrl    pgtype.Text
	UpdatedAt      pgtype.Timestamptz
	TenantID       pgtype.UUID
	Revision_2     int32
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePost,
		arg.ID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Tags,
		arg.Deadline,
		arg.ScheduledAt,
		arg.PublishedAt,
		arg.Excerpt,
		arg.CoverImage,
		arg.Attachments,
		arg.PublishHistory,
		arg.Revision,
		arg.RevisionSha,
		arg.Content,
		arg.TelegramUrl,
		arg.UpdatedAt,
		arg.TenantID,
		arg.Revision_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPost = `-- name: UpsertPost :exec
INSERT INTO posts (
    id, tenant_id, author_id, title, slug, status,
    tags, deadline, scheduled_at, published_at,
    excerpt, cover_image, attachments, publish_history,
    revision, revision_sha, content, telegram_url,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20
)
ON CONFLICT (id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    author_id = EXCLUDED.author_id,
    title = EXCLUDED.title,
    slug = EXCLUDED.slug,
    status = EXCLUDED.status,
    tags = EXCLUDED.tags,
    deadline = EXCLUDED.deadline,
    scheduled_at = EXCLUDED.scheduled_at,
    published_at = EXCLUDED.published_at,
    excerpt = EXCLUDED.excerpt,
    cover_image = EXCLUDED.cover_image,
    attachments = EXCLUDED.attachments,
    publish_history = EXCLUDED.publish_history,
    revision = EXCLUDED.revision,
    revision_sha = EXCLUDED.revision_sha,
    content = EXCLUDED.content,
    telegram_url = EXCLUDED.telegram_url,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertPostParams struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	AuthorID       pgtype.UUID
	Title          string
	Slug           string
	Status         string
	Tags           []byte
	Deadline       pgtype.Timestamptz
	ScheduledAt    pgtype.Timestamptz
	PublishedAt    pgtype.Timestamptz
	Excerpt        pgtype.Text
	CoverImage     []byte
	Attachments    []byte
	PublishHistory []byte
	Revision       int32
	RevisionSha    pgtype.Text
	Content        string
	TelegramUrl    pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) error {
	_, err := q.db.Exec(ctx, upsertPost,
		arg.ID,
		arg.TenantID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Tags,
		arg.Deadline,
		arg.ScheduledAt,
		arg.PublishedAt,
		arg.Excerpt,
		arg.CoverImage,
		arg.Attachments,
		arg.PublishHistory,
		arg.Revision,
		arg.RevisionSha,
		arg.Content,
		arg.TelegramUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
