// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, user_id, prefix, secret_hash, csrf_token, created_at, expires_at, last_used_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateSessionParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Prefix     string
	SecretHash string
	CsrfToken  string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Prefix,
		arg.SecretHash,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :execrows
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByPrefix = `-- name: GetSessionByPrefix :one
SELECT id, user_id, prefix, secret_hash, csrf_token, created_at, expires_at, last_used_at
FROM sessions
WHERE prefix = $1
`

func (q *Queries) GetSessionByPrefix(ctx context.Context, prefix string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByPrefix, prefix)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prefix,
		&i.SecretHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, prefix, secret_hash, csrf_token, created_at, expires_at, last_used_at
FROM sessions
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Prefix,
			&i.SecretHash,
			&i.CsrfToken,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionCSRFToken = `-- name: UpdateSessionCSRFToken :execrows
UPDATE sessions SET csrf_token = $1 WHERE id = $2
`

type UpdateSessionCSRFTokenParams struct {
	CsrfToken string
	ID        pgtype.UUID
}

func (q *Queries) UpdateSessionCSRFToken(ctx context.Context, arg UpdateSessionCSRFTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionCSRFToken, arg.CsrfToken, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionLastUsedAt = `-- name: UpdateSessionLastUsedAt :execrows
UPDATE sessions SET last_used_at = $1 WHERE id = $2
`

type UpdateSessionLastUsedAtParams struct {
	LastUsedAt pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) UpdateSessionLastUsedAt(ctx context.Context, arg UpdateSessionLastUsedAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionLastUsedAt, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
