// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (
    id, user_id, prefix, secret_hash, name, created_at, expires_at, last_used_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateTokenParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Prefix     string
	SecretHash string
	Name       string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken,
		arg.ID,
		arg.UserID,
		arg.Prefix,
		arg.SecretHash,
		arg.Name,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteToken = `-- name: DeleteToken :execrows
DELETE FROM tokens WHERE id = $1
`

func (q *Queries) DeleteToken(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTokenByPrefix = `-- name: GetTokenByPrefix :one
SELECT id, user_id, prefix, secret_hash, name, created_at, expires_at, last_used_at
FROM tokens
WHERE prefix = $1
`

func (q *Queries) GetTokenByPrefix(ctx context.Context, prefix string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByPrefix, prefix)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prefix,
		&i.SecretHash,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, user_id, prefix, secret_hash, name, created_at, expires_at, last_used_at
FROM tokens
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTokensByUser(ctx context.Context, userID pgtype.UUID) ([]Token, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Prefix,
			&i.SecretHash,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenLastUsedAt = `-- name: UpdateTokenLastUsedAt :execrows
UPDATE tokens SET last_used_at = $1 WHERE id = $2
`

type UpdateTokenLastUsedAtParams struct {
	LastUsedAt pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) UpdateTokenLastUsedAt(ctx context.Context, arg UpdateTokenLastUsedAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTokenLastUsedAt, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
