// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapigen

import (
	"time"

	"github.com/google/uuid"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for AttachmentType.
const (
	Audio    AttachmentType = "audio"
	Document AttachmentType = "document"
	Photo    AttachmentType = "photo"
	Video    AttachmentType = "video"
)

// Valid indicates whether the value is a known member of the AttachmentType enum.
func (e AttachmentType) Valid() bool {
	switch e {
	case Audio:
		return true
	case Document:
		return true
	case Photo:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for OutboxEntryStatus.
const (
	OutboxEntryStatusDone     OutboxEntryStatus = "done"
	OutboxEntryStatusFailed   OutboxEntryStatus = "failed"
	OutboxEntryStatusInFlight OutboxEntryStatus = "in_flight"
	OutboxEntryStatusPending  OutboxEntryStatus = "pending"
)

// Valid indicates whether the value is a known member of the OutboxEntryStatus enum.
func (e OutboxEntryStatus) Valid() bool {
	switch e {
	case OutboxEntryStatusDone:
		return true
	case OutboxEntryStatusFailed:
		return true
	case OutboxEntryStatusInFlight:
		return true
	case OutboxEntryStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for OutboxFullEntryStatus.
const (
	OutboxFullEntryStatusDone     OutboxFullEntryStatus = "done"
	OutboxFullEntryStatusFailed   OutboxFullEntryStatus = "failed"
	OutboxFullEntryStatusInFlight OutboxFullEntryStatus = "in_flight"
	OutboxFullEntryStatusPending  OutboxFullEntryStatus = "pending"
)

// Valid indicates whether the value is a known member of the OutboxFullEntryStatus enum.
func (e OutboxFullEntryStatus) Valid() bool {
	switch e {
	case OutboxFullEntryStatusDone:
		return true
	case OutboxFullEntryStatusFailed:
		return true
	case OutboxFullEntryStatusInFlight:
		return true
	case OutboxFullEntryStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for PlanItemDateType.
const (
	PlanItemDateTypeDeadline PlanItemDateType = "deadline"
	PlanItemDateTypeSchedule PlanItemDateType = "schedule"
)

// Valid indicates whether the value is a known member of the PlanItemDateType enum.
func (e PlanItemDateType) Valid() bool {
	switch e {
	case PlanItemDateTypeDeadline:
		return true
	case PlanItemDateTypeSchedule:
		return true
	default:
		return false
	}
}

// Defines values for PostFilterSortBy.
const (
	PostFilterSortByCreatedAt   PostFilterSortBy = "created_at"
	PostFilterSortByDeadline    PostFilterSortBy = "deadline"
	PostFilterSortByScheduledAt PostFilterSortBy = "scheduled_at"
	PostFilterSortByStatus      PostFilterSortBy = "status"
	PostFilterSortByTitle       PostFilterSortBy = "title"
	PostFilterSortByUpdatedAt   PostFilterSortBy = "updated_at"
)

// Valid indicates whether the value is a known member of the PostFilterSortBy enum.
func (e PostFilterSortBy) Valid() bool {
	switch e {
	case PostFilterSortByCreatedAt:
		return true
	case PostFilterSortByDeadline:
		return true
	case PostFilterSortByScheduledAt:
		return true
	case PostFilterSortByStatus:
		return true
	case PostFilterSortByTitle:
		return true
	case PostFilterSortByUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for PostFilterSortOrder.
const (
	PostFilterSortOrderAsc  PostFilterSortOrder = "asc"
	PostFilterSortOrderDesc PostFilterSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the PostFilterSortOrder enum.
func (e PostFilterSortOrder) Valid() bool {
	switch e {
	case PostFilterSortOrderAsc:
		return true
	case PostFilterSortOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for PostStatus.
const (
	PostStatusArchived  PostStatus = "archived"
	PostStatusDraft     PostStatus = "draft"
	PostStatusFailed    PostStatus = "failed"
	PostStatusIdea      PostStatus = "idea"
	PostStatusPublished PostStatus = "published"
	PostStatusReady     PostStatus = "ready"
	PostStatusScheduled PostStatus = "scheduled"
)

// Valid indicates whether the value is a known member of the PostStatus enum.
func (e PostStatus) Valid() bool {
	switch e {
	case PostStatusArchived:
		return true
	case PostStatusDraft:
		return true
	case PostStatusFailed:
		return true
	case PostStatusIdea:
		return true
	case PostStatusPublished:
		return true
	case PostStatusReady:
		return true
	case PostStatusScheduled:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Author Role = "author"
	Editor Role = "editor"
	Owner  Role = "owner"
	Viewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Author:
		return true
	case Editor:
		return true
	case Owner:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for OAuthProviderParam.
const (
	Github OAuthProviderParam = "github"
)

// Valid indicates whether the value is a known member of the OAuthProviderParam enum.
func (e OAuthProviderParam) Valid() bool {
	switch e {
	case Github:
		return true
	default:
		return false
	}
}

// Defines values for ListOutboxParamsStatus.
const (
	ListOutboxParamsStatusDone     ListOutboxParamsStatus = "done"
	ListOutboxParamsStatusFailed   ListOutboxParamsStatus = "failed"
	ListOutboxParamsStatusInFlight ListOutboxParamsStatus = "in_flight"
	ListOutboxParamsStatusPending  ListOutboxParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListOutboxParamsStatus enum.
func (e ListOutboxParamsStatus) Valid() bool {
	switch e {
	case ListOutboxParamsStatusDone:
		return true
	case ListOutboxParamsStatusFailed:
		return true
	case ListOutboxParamsStatusInFlight:
		return true
	case ListOutboxParamsStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ListPostsParamsSortBy.
const (
	CreatedAt   ListPostsParamsSortBy = "created_at"
	Deadline    ListPostsParamsSortBy = "deadline"
	ScheduledAt ListPostsParamsSortBy = "scheduled_at"
	Status      ListPostsParamsSortBy = "status"
	Title       ListPostsParamsSortBy = "title"
	UpdatedAt   ListPostsParamsSortBy = "updated_at"
)

// Valid indicates whether the value is a known member of the ListPostsParamsSortBy enum.
func (e ListPostsParamsSortBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Deadline:
		return true
	case ScheduledAt:
		return true
	case Status:
		return true
	case Title:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListPostsParamsSortOrder.
const (
	ListPostsParamsSortOrderAsc  ListPostsParamsSortOrder = "asc"
	ListPostsParamsSortOrderDesc ListPostsParamsSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListPostsParamsSortOrder enum.
func (e ListPostsParamsSortOrder) Valid() bool {
	switch e {
	case ListPostsParamsSortOrderAsc:
		return true
	case ListPostsParamsSortOrderDesc:
		return true
	default:
		return false
	}
}

// Attachment defines model for Attachment.
type Attachment struct {
	Caption  *string        `json:"caption,omitempty"`
	Id       uuid.UUID      `json:"id"`
	MimeType *string        `json:"mime_type,omitempty"`
	Path     *string        `json:"path,omitempty"`
	Size     *int64         `json:"size,omitempty"`
	Type     AttachmentType `json:"type"`
	Url      *string        `json:"url,omitempty"`
}

// AttachmentType defines model for AttachmentType.
type AttachmentType string

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	AuthorId *uuid.UUID `json:"author_id,omitempty"`
	Content  *string    `json:"content,omitempty"`
	Deadline *time.Time `json:"deadline,omitempty"`
	Excerpt  *string    `json:"excerpt,omitempty"`
	Slug     *string    `json:"slug,omitempty"`
	Tags     *[]string  `json:"tags,omitempty"`
	TenantId *uuid.UUID `json:"tenant_id,omitempty"`
	Title    string     `json:"title"`
}

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	CsrfToken string `json:"csrf_token"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// ExternalLinks defines model for ExternalLinks.
type ExternalLinks struct {
	TelegramUrl *string `json:"telegram_url,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	CsrfToken string    `json:"csrf_token"`
	ExpiresAt time.Time `json:"expires_at"`

	// Role RBAC-роль пользователя
	Role   Role      `json:"role"`
	UserId uuid.UUID `json:"user_id"`
}

// OAuthCallbackQuery defines model for OAuthCallbackQuery.
type OAuthCallbackQuery struct {
	Code  string `json:"code"`
	State string `json:"state"`
}

// OutboxEntry defines model for OutboxEntry.
type OutboxEntry struct {
	EntryId       openapi_types.UUID `json:"entry_id"`
	NextAttemptAt time.Time          `json:"next_attempt_at"`
	PostId        openapi_types.UUID `json:"post_id"`
	Status        OutboxEntryStatus  `json:"status"`
}

// OutboxEntryStatus defines model for OutboxEntry.Status.
type OutboxEntryStatus string

// OutboxFullEntry defines model for OutboxFullEntry.
type OutboxFullEntry struct {
	Attempts      int                   `json:"attempts"`
	CreatedAt     time.Time             `json:"created_at"`
	Id            openapi_types.UUID    `json:"id"`
	Kind          string                `json:"kind"`
	LastError     *string               `json:"last_error,omitempty"`
	MaxAttempts   int                   `json:"max_attempts"`
	NextAttemptAt time.Time             `json:"next_attempt_at"`
	PostId        openapi_types.UUID    `json:"post_id"`
	Status        OutboxFullEntryStatus `json:"status"`
	TenantId      openapi_types.UUID    `json:"tenant_id"`
	UpdatedAt     time.Time             `json:"updated_at"`
}

// OutboxFullEntryStatus defines model for OutboxFullEntry.Status.
type OutboxFullEntryStatus string

// PlanItem defines model for PlanItem.
type PlanItem struct {
	Date     time.Time        `json:"date"`
	DateType PlanItemDateType `json:"date_type"`
	Id       string           `json:"id"`
	Slug     string           `json:"slug"`

	// Status Lifecycle статус поста
	Status PostStatus `json:"status"`
	Title  string     `json:"title"`
}

// PlanItemDateType defines model for PlanItem.DateType.
type PlanItemDateType string

// Post defines model for Post.
type Post struct {
	Attachments    *[]Attachment     `json:"attachments,omitempty"`
	AuthorId       uuid.UUID         `json:"author_id"`
	Content        string            `json:"content"`
	CoverImage     *Attachment       `json:"cover_image,omitempty"`
	CreatedAt      time.Time         `json:"created_at"`
	Deadline       *time.Time        `json:"deadline,omitempty"`
	Excerpt        *string           `json:"excerpt,omitempty"`
	External       ExternalLinks     `json:"external"`
	Id             uuid.UUID         `json:"id"`
	PublishHistory *[]PublishAttempt `json:"publish_history,omitempty"`
	PublishedAt    *time.Time        `json:"published_at,omitempty"`
	Revision       int               `json:"revision"`
	RevisionSha    *string           `json:"revision_sha,omitempty"`
	ScheduledAt    *time.Time        `json:"scheduled_at,omitempty"`
	Slug           string            `json:"slug"`

	// Status Lifecycle статус поста
	Status    PostStatus `json:"status"`
	Tags      *[]string  `json:"tags,omitempty"`
	TenantId  uuid.UUID  `json:"tenant_id"`
	Title     string     `json:"title"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// PostFilter Реплика core.PostFilter — для документирования query-params /posts.
// Не используется напрямую в request body.
type PostFilter struct {
	AuthorId  *uuid.UUID           `json:"author_id,omitempty"`
	Limit     *int                 `json:"limit,omitempty"`
	Offset    *int                 `json:"offset,omitempty"`
	Search    *string              `json:"search,omitempty"`
	SortBy    *PostFilterSortBy    `json:"sort_by,omitempty"`
	SortOrder *PostFilterSortOrder `json:"sort_order,omitempty"`
	Statuses  *[]PostStatus        `json:"statuses,omitempty"`
	Tags      *[]string            `json:"tags,omitempty"`
	TenantId  *uuid.UUID           `json:"tenant_id,omitempty"`
}

// PostFilterSortBy defines model for PostFilter.SortBy.
type PostFilterSortBy string

// PostFilterSortOrder defines model for PostFilter.SortOrder.
type PostFilterSortOrder string

// PostStatus Lifecycle статус поста
type PostStatus string

// PublishAttempt defines model for PublishAttempt.
type PublishAttempt struct {
	At time.Time `json:"at"`

	// Duration Длительность попытки в наносекундах (Go time.Duration)
	Duration  int64     `json:"duration"`
	Error     *string   `json:"error,omitempty"`
	Id        uuid.UUID `json:"id"`
	MessageId *string   `json:"message_id,omitempty"`

	// ResponsePayload Сырой JSON-ответ внешней платформы (опционально)
	ResponsePayload *string `json:"response_payload,omitempty"`
	RetryAttempt    int     `json:"retry_attempt"`
	Status          string  `json:"status"`
	Target          string  `json:"target"`
}

// Role RBAC-роль пользователя
type Role string

// Stats Карта `status -> count` (например `{"idea": 3, "draft": 1, ...}`).
// Возвращается напрямую из core.PostService.GetStats.
type Stats map[string]int

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	Tags []string `json:"tags"`
}

// UpdatePostRequest defines model for UpdatePostRequest.
type UpdatePostRequest struct {
	Content     *string    `json:"content,omitempty"`
	Deadline    *time.Time `json:"deadline,omitempty"`
	Excerpt     *string    `json:"excerpt,omitempty"`
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`

	// Status Lifecycle статус поста
	Status   *PostStatus `json:"status,omitempty"`
	Tags     *[]string   `json:"tags,omitempty"`
	TenantId *uuid.UUID  `json:"tenant_id,omitempty"`
	Title    *string     `json:"title,omitempty"`
}

// OAuthProviderParam defines model for OAuthProviderParam.
type OAuthProviderParam string

// PostIdParam defines model for PostIdParam.
type PostIdParam = uuid.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// ListOutboxParams defines parameters for ListOutbox.
type ListOutboxParams struct {
	Status *ListOutboxParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOutboxParamsStatus defines parameters for ListOutbox.
type ListOutboxParamsStatus string

// GetPlanParams defines parameters for GetPlan.
type GetPlanParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListPostsParams defines parameters for ListPosts.
type ListPostsParams struct {
	// Status Фильтр по PostStatus (можно повторять)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Tag Фильтр по тегу (можно повторять)
	Tag       *string                   `form:"tag,omitempty" json:"tag,omitempty"`
	Search    *string                   `form:"search,omitempty" json:"search,omitempty"`
	SortBy    *ListPostsParamsSortBy    `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	SortOrder *ListPostsParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`
	Limit     *int                      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *int                      `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListPostsParamsSortBy defines parameters for ListPosts.
type ListPostsParamsSortBy string

// ListPostsParamsSortOrder defines parameters for ListPosts.
type ListPostsParamsSortOrder string

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = LoginRequest

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = CreatePostRequest

// UpdatePostJSONRequestBody defines body for UpdatePost for application/json ContentType.
type UpdatePostJSONRequestBody = UpdatePostRequest
