// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlitedb

import (
	"context"
)

const appendAuditLog = `-- name: AppendAuditLog :exec
INSERT INTO audit_log (
    id, occurred_at, tenant_id, actor_id, actor_type, action,
    resource_type, resource_id, outcome, ip, user_agent, metadata
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendAuditLogParams struct {
	ID           string
	OccurredAt   string
	TenantID     string
	ActorID      string
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   string
	Outcome      string
	Ip           string
	UserAgent    string
	Metadata     string
}

func (q *Queries) AppendAuditLog(ctx context.Context, arg AppendAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, appendAuditLog,
		arg.ID,
		arg.OccurredAt,
		arg.TenantID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, occurred_at, tenant_id, actor_id, actor_type, action,
       resource_type, resource_id, outcome, ip, user_agent, metadata
FROM audit_log
WHERE (?1 = '' OR tenant_id = ?1)
  AND (?2 = '' OR actor_id = ?2)
  AND (?3 = '' OR action = ?3)
ORDER BY occurred_at DESC
LIMIT ?4
`

type ListAuditLogParams struct {
	TenantID interface{}
	ActorID  interface{}
	Action   interface{}
	Lim      int64
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.TenantID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Outcome,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
