// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
)

type OauthAccount struct {
	ID         string
	UserID     string
	Provider   string
	ExternalID string
	Email      string
	CreatedAt  string
}

type OutboxEntry struct {
	ID            string
	PostID        string
	TenantID      string
	Kind          string
	Status        string
	Attempts      int64
	MaxAttempts   int64
	NextAttemptAt string
	LastError     string
	CreatedAt     string
	UpdatedAt     string
}

type Post struct {
	ID             string
	TenantID       string
	AuthorID       string
	Title          string
	Slug           string
	Status         string
	Tags           string
	Deadline       sql.NullString
	ScheduledAt    sql.NullString
	PublishedAt    sql.NullString
	Excerpt        sql.NullString
	CoverImage     sql.NullString
	Attachments    string
	PublishHistory string
	Revision       int64
	RevisionSha    sql.NullString
	Content        string
	TelegramUrl    sql.NullString
	CreatedAt      string
	UpdatedAt      string
}

type Session struct {
	ID         string
	UserID     string
	Prefix     string
	SecretHash string
	CsrfToken  string
	CreatedAt  string
	ExpiresAt  string
	LastUsedAt sql.NullString
}

type Token struct {
	ID         string
	UserID     string
	Prefix     string
	SecretHash string
	Name       string
	CreatedAt  string
	ExpiresAt  sql.NullString
	LastUsedAt sql.NullString
}

type User struct {
	ID           string
	TenantID     string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}
