// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package sqlitedb

import (
	"context"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO oauth_accounts (
    id, user_id, provider, external_id, email, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type CreateOAuthAccountParams struct {
	ID         string
	UserID     string
	Provider   string
	ExternalID string
	Email      string
	CreatedAt  string
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ExternalID,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :execrows
DELETE FROM oauth_accounts WHERE id = ?
`

func (q *Queries) DeleteOAuthAccount(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOAuthAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOAuthAccountByExternalID = `-- name: GetOAuthAccountByExternalID :one
SELECT id, user_id, provider, external_id, email, created_at
FROM oauth_accounts
WHERE provider = ? AND external_id = ?
`

type GetOAuthAccountByExternalIDParams struct {
	Provider   string
	ExternalID string
}

func (q *Queries) GetOAuthAccountByExternalID(ctx context.Context, arg GetOAuthAccountByExternalIDParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByExternalID, arg.Provider, arg.ExternalID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthAccountsByUser = `-- name: ListOAuthAccountsByUser :many
SELECT id, user_id, provider, external_id, email, created_at
FROM oauth_accounts
WHERE user_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListOAuthAccountsByUser(ctx context.Context, userID string) ([]OauthAccount, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthAccount
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ExternalID,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
