// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlitedb

import (
	"context"
)

const claimNextOutbox = `-- name: ClaimNextOutbox :one
UPDATE outbox_entries
SET status = 'in_flight', updated_at = ?
WHERE id = (
    SELECT id FROM outbox_entries oe
    WHERE oe.status = 'pending' AND oe.next_attempt_at <= ?
    ORDER BY oe.next_attempt_at ASC
    LIMIT 1
)
RETURNING id, post_id, tenant_id, kind, status, attempts, max_attempts,
          next_attempt_at, last_error, created_at, updated_at
`

type ClaimNextOutboxParams struct {
	UpdatedAt     string
	NextAttemptAt string
}

func (q *Queries) ClaimNextOutbox(ctx context.Context, arg ClaimNextOutboxParams) (OutboxEntry, error) {
	row := q.db.QueryRowContext(ctx, claimNextOutbox, arg.UpdatedAt, arg.NextAttemptAt)
	var i OutboxEntry
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.TenantID,
		&i.Kind,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutbox = `-- name: CreateOutbox :exec
INSERT INTO outbox_entries (
    id, post_id, tenant_id, kind, status, attempts, max_attempts,
    next_attempt_at, last_error, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOutboxParams struct {
	ID            string
	PostID        string
	TenantID      string
	Kind          string
	Status        string
	Attempts      int64
	MaxAttempts   int64
	NextAttemptAt string
	LastError     string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateOutbox(ctx context.Context, arg CreateOutboxParams) error {
	_, err := q.db.ExecContext(ctx, createOutbox,
		arg.ID,
		arg.PostID,
		arg.TenantID,
		arg.Kind,
		arg.Status,
		arg.Attempts,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOutboxByID = `-- name: GetOutboxByID :one
SELECT id, post_id, tenant_id, kind, status, attempts, max_attempts,
       next_attempt_at, last_error, created_at, updated_at
FROM outbox_entries WHERE id = ?
`

func (q *Queries) GetOutboxByID(ctx context.Context, id string) (OutboxEntry, error) {
	row := q.db.QueryRowContext(ctx, getOutboxByID, id)
	var i OutboxEntry
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.TenantID,
		&i.Kind,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutboxAll = `-- name: ListOutboxAll :many
SELECT id, post_id, tenant_id, kind, status, attempts, max_attempts,
       next_attempt_at, last_error, created_at, updated_at
FROM outbox_entries
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListOutboxAll(ctx context.Context, limit int64) ([]OutboxEntry, error) {
	rows, err := q.db.QueryContext(ctx, listOutboxAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEntry
	for rows.Next() {
		var i OutboxEntry
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.TenantID,
			&i.Kind,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxByStatus = `-- name: ListOutboxByStatus :many
SELECT id, post_id, tenant_id, kind, status, attempts, max_attempts,
       next_attempt_at, last_error, created_at, updated_at
FROM outbox_entries
WHERE status = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListOutboxByStatusParams struct {
	Status string
	Limit  int64
}

func (q *Queries) ListOutboxByStatus(ctx context.Context, arg ListOutboxByStatusParams) ([]OutboxEntry, error) {
	rows, err := q.db.QueryContext(ctx, listOutboxByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEntry
	for rows.Next() {
		var i OutboxEntry
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.TenantID,
			&i.Kind,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxDone = `-- name: MarkOutboxDone :execrows
UPDATE outbox_entries
SET status = 'done', updated_at = ?
WHERE id = ?
`

type MarkOutboxDoneParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) MarkOutboxDone(ctx context.Context, arg MarkOutboxDoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxDone, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxFailed = `-- name: MarkOutboxFailed :execrows
UPDATE outbox_entries
SET status = 'failed', last_error = ?, updated_at = ?
WHERE id = ?
`

type MarkOutboxFailedParams struct {
	LastError string
	UpdatedAt string
	ID        string
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxFailed, arg.LastError, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxRetry = `-- name: MarkOutboxRetry :execrows
UPDATE outbox_entries
SET status = 'pending', attempts = ?, next_attempt_at = ?, last_error = ?, updated_at = ?
WHERE id = ?
`

type MarkOutboxRetryParams struct {
	Attempts      int64
	NextAttemptAt string
	LastError     string
	UpdatedAt     string
	ID            string
}

func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRetry,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sweepStuckOutbox = `-- name: SweepStuckOutbox :execrows
UPDATE outbox_entries
SET status = 'pending', updated_at = ?
WHERE status = 'in_flight' AND updated_at < ?
`

type SweepStuckOutboxParams struct {
	UpdatedAt   string
	UpdatedAt_2 string
}

func (q *Queries) SweepStuckOutbox(ctx context.Context, arg SweepStuckOutboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sweepStuckOutbox, arg.UpdatedAt, arg.UpdatedAt_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
