// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (
    id, tenant_id, author_id, title, slug, status,
    tags, deadline, scheduled_at, published_at,
    excerpt, cover_image, attachments, publish_history,
    revision, revision_sha, content, telegram_url,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?
)
`

type CreatePostParams struct {
	ID             string
	TenantID       string
	AuthorID       string
	Title          string
	Slug           string
	Status         string
	Tags           string
	Deadline       sql.NullString
	ScheduledAt    sql.NullString
	PublishedAt    sql.NullString
	Excerpt        sql.NullString
	CoverImage     sql.NullString
	Attachments    string
	PublishHistory string
	Revision       int64
	RevisionSha    sql.NullString
	Content        string
	TelegramUrl    sql.NullString
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.TenantID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Tags,
		arg.Deadline,
		arg.ScheduledAt,
		arg.PublishedAt,
		arg.Excerpt,
		arg.CoverImage,
		arg.Attachments,
		arg.PublishHistory,
		arg.Revision,
		arg.RevisionSha,
		arg.Content,
		arg.TelegramUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts
WHERE id = ? AND tenant_id = ?
`

type DeletePostParams struct {
	ID       string
	TenantID string
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPostByID = `-- name: GetPostByID :one
SELECT
    id, tenant_id, author_id, title, slug, status,
    tags, deadline, scheduled_at, published_at,
    excerpt, cover_image, attachments, publish_history,
    revision, revision_sha, content, telegram_url,
    created_at, updated_at
FROM posts
WHERE id = ?
`

func (q *Queries) GetPostByID(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Tags,
		&i.Deadline,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Excerpt,
		&i.CoverImage,
		&i.Attachments,
		&i.PublishHistory,
		&i.Revision,
		&i.RevisionSha,
		&i.Content,
		&i.TelegramUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByIDInTenant = `-- name: GetPostByIDInTenant :one
SELECT
    id, tenant_id, author_id, title, slug, status,
    tags, deadline, scheduled_at, published_at,
    excerpt, cover_image, attachments, publish_history,
    revision, revision_sha, content, telegram_url,
    created_at, updated_at
FROM posts
WHERE id = ? AND tenant_id = ?
`

type GetPostByIDInTenantParams struct {
	ID       string
	TenantID string
}

func (q *Queries) GetPostByIDInTenant(ctx context.Context, arg GetPostByIDInTenantParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByIDInTenant, arg.ID, arg.TenantID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Tags,
		&i.Deadline,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Excerpt,
		&i.CoverImage,
		&i.Attachments,
		&i.PublishHistory,
		&i.Revision,
		&i.RevisionSha,
		&i.Content,
		&i.TelegramUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT
    id, tenant_id, author_id, title, slug, status,
    tags, deadline, scheduled_at, published_at,
    excerpt, cover_image, attachments, publish_history,
    revision, revision_sha, content, telegram_url,
    created_at, updated_at
FROM posts
WHERE tenant_id = ? AND slug = ?
`

type GetPostBySlugParams struct {
	TenantID string
	Slug     string
}

func (q *Queries) GetPostBySlug(ctx context.Context, arg GetPostBySlugParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, arg.TenantID, arg.Slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Tags,
		&i.Deadline,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Excerpt,
		&i.CoverImage,
		&i.Attachments,
		&i.PublishHistory,
		&i.Revision,
		&i.RevisionSha,
		&i.Content,
		&i.TelegramUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const postExistsByID = `-- name: PostExistsByID :one
SELECT EXISTS(SELECT 1 FROM posts WHERE id = ?) AS found
`

func (q *Queries) PostExistsByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, postExistsByID, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const updatePost = `-- name: UpdatePost :execrows
UPDATE posts
SET
    author_id = ?,
    title = ?,
    slug = ?,
    status = ?,
    tags = ?,
    deadline = ?,
    scheduled_at = ?,
    published_at = ?,
    excerpt = ?,
    cover_image = ?,
    attachments = ?,
    publish_history = ?,
    revision = ?,
    revision_sha = ?,
    content = ?,
    telegram_url = ?,
    updated_at = ?
WHERE id = ? AND tenant_id = ? AND revision = ?
`

type UpdatePostParams struct {
	AuthorID       string
	Title          string
	Slug           string
	Status         string
	Tags           string
	Deadline       sql.NullString
	ScheduledAt    sql.NullString
	PublishedAt    sql.NullString
	Excerpt        sql.NullString
	CoverImage     sql.NullString
	Attachments    string
	PublishHistory string
	Revision       int64
	RevisionSha    sql.NullString
	Content        string
	TelegramUrl    sql.NullString
	UpdatedAt      string
	ID             string
	TenantID       string
	Revision_2     int64
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePost,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Tags,
		arg.Deadline,
		arg.ScheduledAt,
		arg.PublishedAt,
		arg.Excerpt,
		arg.CoverImage,
		arg.Attachments,
		arg.PublishHistory,
		arg.Revision,
		arg.RevisionSha,
		arg.Content,
		arg.TelegramUrl,
		arg.UpdatedAt,
		arg.ID,
		arg.TenantID,
		arg.Revision_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPost = `-- name: UpsertPost :exec
INSERT INTO posts (
    id, tenant_id, author_id, title, slug, status,
    tags, deadline, scheduled_at, published_at,
    excerpt, cover_image, attachments, publish_history,
    revision, revision_sha, content, telegram_url,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    tenant_id = excluded.tenant_id,
    author_id = excluded.author_id,
    title = excluded.title,
    slug = excluded.slug,
    status = excluded.status,
    tags = excluded.tags,
    deadline = excluded.deadline,
    scheduled_at = excluded.scheduled_at,
    published_at = excluded.published_at,
    excerpt = excluded.excerpt,
    cover_image = excluded.cover_image,
    attachments = excluded.attachments,
    publish_history = excluded.publish_history,
    revision = excluded.revision,
    revision_sha = excluded.revision_sha,
    content = excluded.content,
    telegram_url = excluded.telegram_url,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at
`

type UpsertPostParams struct {
	ID             string
	TenantID       string
	AuthorID       string
	Title          string
	Slug           string
	Status         string
	Tags           string
	Deadline       sql.NullString
	ScheduledAt    sql.NullString
	PublishedAt    sql.NullString
	Excerpt        sql.NullString
	CoverImage     sql.NullString
	Attachments    string
	PublishHistory string
	Revision       int64
	RevisionSha    sql.NullString
	Content        string
	TelegramUrl    sql.NullString
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) error {
	_, err := q.db.ExecContext(ctx, upsertPost,
		arg.ID,
		arg.TenantID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Tags,
		arg.Deadline,
		arg.ScheduledAt,
		arg.PublishedAt,
		arg.Excerpt,
		arg.CoverImage,
		arg.Attachments,
		arg.PublishHistory,
		arg.Revision,
		arg.RevisionSha,
		arg.Content,
		arg.TelegramUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
