// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, user_id, prefix, secret_hash, csrf_token, created_at, expires_at, last_used_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateSessionParams struct {
	ID         string
	UserID     string
	Prefix     string
	SecretHash string
	CsrfToken  string
	CreatedAt  string
	ExpiresAt  string
	LastUsedAt sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Prefix,
		arg.SecretHash,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :execrows
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByPrefix = `-- name: GetSessionByPrefix :one
SELECT id, user_id, prefix, secret_hash, csrf_token, created_at, expires_at, last_used_at
FROM sessions
WHERE prefix = ?
`

func (q *Queries) GetSessionByPrefix(ctx context.Context, prefix string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByPrefix, prefix)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prefix,
		&i.SecretHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, prefix, secret_hash, csrf_token, created_at, expires_at, last_used_at
FROM sessions
WHERE user_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Prefix,
			&i.SecretHash,
			&i.CsrfToken,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionCSRFToken = `-- name: UpdateSessionCSRFToken :execrows
UPDATE sessions SET csrf_token = ? WHERE id = ?
`

type UpdateSessionCSRFTokenParams struct {
	CsrfToken string
	ID        string
}

func (q *Queries) UpdateSessionCSRFToken(ctx context.Context, arg UpdateSessionCSRFTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionCSRFToken, arg.CsrfToken, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSessionLastUsedAt = `-- name: UpdateSessionLastUsedAt :execrows
UPDATE sessions SET last_used_at = ? WHERE id = ?
`

type UpdateSessionLastUsedAtParams struct {
	LastUsedAt sql.NullString
	ID         string
}

func (q *Queries) UpdateSessionLastUsedAt(ctx context.Context, arg UpdateSessionLastUsedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionLastUsedAt, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
