// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (
    id, user_id, prefix, secret_hash, name, created_at, expires_at, last_used_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateTokenParams struct {
	ID         string
	UserID     string
	Prefix     string
	SecretHash string
	Name       string
	CreatedAt  string
	ExpiresAt  sql.NullString
	LastUsedAt sql.NullString
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.UserID,
		arg.Prefix,
		arg.SecretHash,
		arg.Name,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteToken = `-- name: DeleteToken :execrows
DELETE FROM tokens WHERE id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTokenByPrefix = `-- name: GetTokenByPrefix :one
SELECT id, user_id, prefix, secret_hash, name, created_at, expires_at, last_used_at
FROM tokens
WHERE prefix = ?
`

func (q *Queries) GetTokenByPrefix(ctx context.Context, prefix string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByPrefix, prefix)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Prefix,
		&i.SecretHash,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, user_id, prefix, secret_hash, name, created_at, expires_at, last_used_at
FROM tokens
WHERE user_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListTokensByUser(ctx context.Context, userID string) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Prefix,
			&i.SecretHash,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenLastUsedAt = `-- name: UpdateTokenLastUsedAt :execrows
UPDATE tokens SET last_used_at = ? WHERE id = ?
`

type UpdateTokenLastUsedAtParams struct {
	LastUsedAt sql.NullString
	ID         string
}

func (q *Queries) UpdateTokenLastUsedAt(ctx context.Context, arg UpdateTokenLastUsedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTokenLastUsedAt, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
